#release configuration
#Sun Apr 12 14:19:12 GMT+03:00 2026
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.f216\:sports-manager=1.0.1-SNAPSHOT
project.rel.com.f216\:sports-manager=1.0.0
project.scm.com.f216\:sports-manager.developerConnection=scm\:git\:https\://github.com/tunctarim/sports-manager.git
project.scm.com.f216\:sports-manager.tag=HEAD
project.scm.com.f216\:sports-manager.url=https\://github.com/tunctarim/sports-manager
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=sports-manager-1.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/tunctarim/sports-manager.git
